name: Wormhole
version: '${version}'
api-version: '1.21'
authors: [Antritus]
description: Wormhole teleportation and home management system!
website: astral.bet

# The main plugin
main: bet.astral.wormhole.plugin.WormholePlugin
# Makes sure the plugin is used by paper servers and not spigot servers
# Loads commands
bootstrapper: bet.astral.wormhole.plugin.Bootstrap
# Loads the libraries for the plugin
loader: bet.astral.wormhole.plugin.Initialize
